UPDATE books SET title = 'The Little Prince', author = 'Antoine de Saint-Exupéry', genre = 'Fiction', status = 'checked in', due_date = null WHERE barcode = 'B001';
UPDATE books SET title = 'Dune', author = 'Frank Herbert', genre = 'Science Fiction', status = 'checked out', due_date = '2024-12-01' WHERE barcode = 'B002';
UPDATE books SET title = '1984', author = 'George Orwell', genre = 'Dystopian', status = 'checked in', due_date = null WHERE barcode = 'B004';
UPDATE books SET title = 'The Great Gatsby', author = 'F. Scott Fitzgerald', genre = 'Fiction', status = 'checked out', due_date = '2024-12-05' WHERE barcode = 'B005';
UPDATE books SET title = 'The Catcher in the Rye', author = 'J.D. Salinger', genre = 'Fiction', status = 'checked in', due_date = null WHERE barcode = 'B006';
UPDATE books SET title = 'Moby Dick', author = 'Herman Melville', genre = 'Adventure', status = 'checked in', due_date = null WHERE barcode = 'B007';
UPDATE books SET title = 'The Hobbit', author = 'J.R.R. Tolkien', genre = 'Fantasy', status = 'checked out', due_date = '2024-12-10' WHERE barcode = 'B008';
UPDATE books SET title = 'Pride and Prejudice', author = 'Jane Austen', genre = 'Romance', status = 'checked in', due_date = null WHERE barcode = 'B009';
UPDATE books SET title = 'War and Peace', author = 'Leo Tolstoy', genre = 'Historical', status = 'checked out', due_date = '2024-12-12' WHERE barcode = 'B010';
UPDATE books SET title = 'The Art of War', author = 'Sun Tzu', genre = 'Non-Fiction', status = 'checked in', due_date = null WHERE barcode = 'B011';
UPDATE books SET title = 'The Road', author = 'Cormac McCarthy', genre = 'Post-Apocalyptic', status = 'checked in', due_date = null WHERE barcode = 'B012';
UPDATE books SET title = 'Brave New World', author = 'Aldous Huxley', genre = 'Dystopian', status = 'checked in', due_date = null WHERE barcode = 'B013';
UPDATE books SET title = 'Crime and Punishment', author = 'Fyodor Dostoevsky', genre = 'Crime', status = 'checked in', due_date = null WHERE barcode = 'B014';
UPDATE books SET title = 'Jane Eyre', author = 'Charlotte Brontë', genre = 'Fiction', status = 'checked out', due_date = '2024-12-15' WHERE barcode = 'B015';
UPDATE books SET title = 'Wuthering Heights', author = 'Emily Brontë', genre = 'Romance', status = 'checked in', due_date = null WHERE barcode = 'B016';
UPDATE books SET title = 'The Divine Comedy', author = 'Dante Alighieri', genre = 'Poetry', status = 'checked in', due_date = null WHERE barcode = 'B017';
UPDATE books SET title = 'The Iliad', author = 'Homer', genre = 'Classics', status = 'checked in', due_date = null WHERE barcode = 'B018';
UPDATE books SET title = 'Frankenstein', author = 'Mary Shelley', genre = 'Horror', status = 'checked in', due_date = null WHERE barcode = 'B019';
UPDATE books SET title = 'Dracula', author = 'Bram Stoker', genre = 'Horror', status = 'checked out', due_date = '2024-12-20' WHERE barcode = 'B020';
UPDATE books SET title = 'To Kill a Mockingbird', author = 'Harper Lee', genre = 'Fiction', status = 'checked in', due_date = null WHERE barcode = 'B003';
